name: DiscordNotificationPush
on: push
jobs: 
  - name: Notify
    uses: rjstone/discord-webhook-notify@v1
    with:
      severity: info
      webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
      details: 'There is a push on the repository'