name: Push Notification
on: push
jobs:
  push:
    name: Push notification
    runs-on: ubuntu-latest
    steps:
      - name: "Push to discord"
        uses: rjstone/discord-webhook-notify@v1
        with:
          details: "There is a push"
          severity: info
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}